DEFAULT_OUTPUT_DIR = '~/unmixer'

GUITAR_TRACK_NAME = 'guitar'
OTHER_TRACK_NAME = 'other'
PIANO_TRACK_NAME = 'piano'
DEFAULT_OTHER_TRACK_NAME = OTHER_TRACK_NAME
ALLOWED_OTHER_TRACK_NAMES = (GUITAR_TRACK_NAME, PIANO_TRACK_NAME, OTHER_TRACK_NAME)  # in display order

FLAC_FORMAT = 'flac'
MP3_FORMAT = 'mp3'
WAV_FORMAT = 'wav'
DEFAULT_ISOLATED_TRACK_FORMAT = WAV_FORMAT
ISOLATED_TRACK_FORMATS = {FLAC_FORMAT, MP3_FORMAT, WAV_FORMAT}

MP3_PRESET_MIN = 2  # Better quality
MP3_PRESET_MAX = 7  # Faster encoding
DEFAULT_MP3_PRESET = MP3_PRESET_MIN

# Reference: https://en.wikipedia.org/wiki/MP3#Bit_rate
ALLOWED_MP3_BITRATES_KBPS = (96, 112, 128, 160, 192, 224, 256, 320)
DEFAULT_MP3_BITRATE_KBPS = 320

WAV_DEPTH_INT16 = 'int16'
WAV_DEPTH_INT24 = 'int24'
WAV_DEPTH_FLOAT32 = 'float32'
DEFAULT_WAV_DEPTH = WAV_DEPTH_INT16
ALLOWED_WAV_BIT_DEPTHS = (WAV_DEPTH_INT16, WAV_DEPTH_INT24, WAV_DEPTH_FLOAT32)  # in display order
