DEFAULT_OUTPUT_DIR = '~/unmixer'

GUITAR_TRACK_NAME = 'guitar'
OTHER_TRACK_NAME = 'other'
PIANO_TRACK_NAME = 'piano'
DEFAULT_OTHER_TRACK_NAME = OTHER_TRACK_NAME
ALLOWED_OTHER_TRACK_NAMES = (GUITAR_TRACK_NAME, PIANO_TRACK_NAME, OTHER_TRACK_NAME)  # in display order

MP3_FORMAT = 'mp3'
WAV_FORMAT = 'wav'
DEFAULT_ISOLATED_TRACK_FORMAT = WAV_FORMAT
ISOLATED_TRACK_FORMATS = {MP3_FORMAT, WAV_FORMAT}
